const fs = require('fs');
const path = require('path');

const dictionary = {
  // Grade 1
  'apple': { t: 'n. 苹果', u: '用作名词，指代一种水果。', e: ['I ate an apple today.', 'She bought some red apples.'] },
  'book': { t: 'n. 书，书籍', u: '用作名词，指供阅读的印刷品。', e: ['He is reading a book.', 'Put the book on the desk.'] },
  'cat': { t: 'n. 猫', u: '用作名词，指一种常见的宠物。', e: ['My cat is sleeping.', 'The cat caught a mouse.'] },
  'dog': { t: 'n. 狗', u: '用作名词，指一种常见的家养动物。', e: ['The dog barked loudly.', 'He walked his dog in the park.'] },
  'egg': { t: 'n. 蛋，鸡蛋', u: '用作名词，指鸟类或家禽产的卵。', e: ['I had a boiled egg for breakfast.', 'She cracked an egg into the bowl.'] },
  'fish': { t: 'n. 鱼', u: '用作名词，水生动物。', e: ['They caught a big fish.', 'Fish swim in the river.'] },
  'girl': { t: 'n. 女孩', u: '用作名词，指女性儿童或青少年。', e: ['The little girl is smiling.', 'She is a smart girl.'] },
  'hand': { t: 'n. 手', u: '用作名词，人体部位。', e: ['Wash your hands before eating.', 'He raised his hand.'] },
  'ice': { t: 'n. 冰', u: '用作名词，冻结的水。', e: ['Put some ice in my drink.', 'The lake is covered with ice.'] },
  'juice': { t: 'n. 果汁', u: '用作名词，水果压榨出的液体。', e: ['I want some orange juice.', 'She spilled juice on the table.'] },
  'kite': { t: 'n. 风筝', u: '用作名词，一种依靠风力飞行的玩具。', e: ['The children are flying a kite.', 'My kite got stuck in a tree.'] },
  'lion': { t: 'n. 狮子', u: '用作名词，一种大型猫科动物。', e: ['The lion roared in the zoo.', 'Lions are wild animals.'] },
  'milk': { t: 'n. 牛奶', u: '用作名词，哺乳动物分泌的白色营养液体。', e: ['Drink a glass of milk.', 'We need more milk for the recipe.'] },
  'nose': { t: 'n. 鼻子', u: '用作名词，人体嗅觉和呼吸器官。', e: ['He has a long nose.', 'A dog has a good nose.'] },
  'orange': { t: 'n. 橘子；橙色', u: '用作名词，指水果或颜色。', e: ['Would you like an orange?', 'The sky turned orange at sunset.'] },
  'pig': { t: 'n. 猪', u: '用作名词，一种家畜。', e: ['The pig is eating.', 'They keep pigs on the farm.'] },
  'queen': { t: 'n. 女王', u: '用作名词，女性君主。', e: ['The queen waved to the crowd.', 'She dressed like a queen.'] },
  'red': { t: 'adj. 红色的', u: '用作形容词，表示一种颜色。', e: ['She wore a red dress.', 'Apples can be red or green.'] },
  'sun': { t: 'n. 太阳', u: '用作名词，太阳系的中心天体。', e: ['The sun is shining brightly.', 'Don\'t look directly at the sun.'] },
  'tree': { t: 'n. 树', u: '用作名词，多年生木本植物。', e: ['There is a big tree in the yard.', 'The bird flew into the tree.'] },
  'box': { t: 'n. 盒子', u: '用作名词，一种容器。', e: ['Put the toys in the box.', 'The box is heavy.'] },
  'cup': { t: 'n. 杯子', u: '用作名词，一种饮水容器。', e: ['He poured tea into the cup.', 'I need a cup of coffee.'] },
  'desk': { t: 'n. 书桌', u: '用作名词，一种供书写或办公的桌子。', e: ['Her books are on the desk.', 'He sat at his desk.'] },
  'eye': { t: 'n. 眼睛', u: '用作名词，视觉器官。', e: ['Close your eyes.', 'She has blue eyes.'] },
  'face': { t: 'n. 脸', u: '用作名词，面部。', e: ['Wash your face.', 'He had a smile on his face.'] },
  'jump': { t: 'v. 跳跃', u: '用作动词，指离地跳起。', e: ['The frog can jump far.', 'Jump over the puddle.'] },
  'key': { t: 'n. 钥匙', u: '用作名词，开锁的工具。', e: ['I lost my key.', 'Use this key to open the door.'] },

  // Grade 2
  'bike': { t: 'n. 自行车', u: '用作名词，两轮交通工具。', e: ['He rode his bike to school.', 'I bought a new bike.'] },
  'cake': { t: 'n. 蛋糕', u: '用作名词，一种甜点。', e: ['She baked a chocolate cake.', 'Happy birthday! Here is your cake.'] },
  'door': { t: 'n. 门', u: '用作名词，建筑或房间的入口。', e: ['Please close the door.', 'Someone is knocking on the door.'] },
  'ear': { t: 'n. 耳朵', u: '用作名词，听觉器官。', e: ['The rabbit has long ears.', 'Cover your ears.'] },
  'foot': { t: 'n. 脚', u: '用作名词，人或动物用来行走的部位。', e: ['My foot hurts.', 'He stepped on my foot.'] },
  'good': { t: 'adj. 好的', u: '用作形容词，表示优良、令人满意。', e: ['Have a good day.', 'This is a good book.'] },
  'head': { t: 'n. 头', u: '用作名词，人体最高部位。', e: ['He nodded his head.', 'My head aches.'] },
  'kiss': { t: 'v. 亲吻', u: '用作动词，表示喜爱或问候。', e: ['She kissed her baby.', 'They shared a kiss.'] },
  'leg': { t: 'n. 腿', u: '用作名词，支撑身体的部位。', e: ['He broke his leg.', 'The table has four legs.'] },
  'moon': { t: 'n. 月亮', u: '用作名词，地球的天然卫星。', e: ['The moon is full tonight.', 'Look at the beautiful moon.'] },
  'name': { t: 'n. 名字', u: '用作名词，称呼人或事物的词语。', e: ['What is your name?', 'Write your name here.'] },
  'open': { t: 'v. 打开', u: '用作动词，使开启。', e: ['Open the window, please.', 'The store is open.'] },
  'pen': { t: 'n. 钢笔', u: '用作名词，书写工具。', e: ['I need a blue pen.', 'He wrote it with a pen.'] },
  'quick': { t: 'adj. 快的', u: '用作形容词，表示迅速。', e: ['Be quick!', 'She gave a quick answer.'] },
  'room': { t: 'n. 房间', u: '用作名词，建筑物内的空间。', e: ['Clean your room.', 'This room is too small.'] },
  'star': { t: 'n. 星星', u: '用作名词，夜空中的发光天体。', e: ['Look at the bright star.', 'She drew a star on the paper.'] },
  'time': { t: 'n. 时间', u: '用作名词，表示时刻或期间。', e: ['What time is it?', 'It is time to go.'] },
  'van': { t: 'n. 面包车', u: '用作名词，一种厢式货车。', e: ['They drove a white van.', 'Load the boxes into the van.'] },
  'water': { t: 'n. 水', u: '用作名词，透明的液体。', e: ['Drink plenty of water.', 'The water is cold.'] },
  'xray': { t: 'n. X光', u: '用作名词，医学影像技术。', e: ['The doctor took an x-ray.', 'The x-ray showed a broken bone.'] },
  'year': { t: 'n. 年', u: '用作名词，时间单位。', e: ['Happy new year!', 'It takes a year to finish.'] },
  'zoo': { t: 'n. 动物园', u: '用作名词，展览动物的地方。', e: ['We went to the zoo.', 'I saw monkeys at the zoo.'] },
  'bag': { t: 'n. 袋子', u: '用作名词，盛物的容器。', e: ['Put it in the bag.', 'She carried a heavy bag.'] },
  'car': { t: 'n. 汽车', u: '用作名词，一种交通工具。', e: ['He drives a fast car.', 'The car is red.'] },
  'dad': { t: 'n. 爸爸', u: '用作名词，父亲。', e: ['My dad is tall.', 'Dad went to work.'] },
  'eat': { t: 'v. 吃', u: '用作动词，进食。', e: ['Let us eat dinner.', 'Do not eat too much candy.'] },
  'fat': { t: 'adj. 胖的', u: '用作形容词，肥胖的。', e: ['The cat is fat.', 'Eating too much makes you fat.'] },
  'get': { t: 'v. 得到', u: '用作动词，获得或到达。', e: ['Did you get the message?', 'Go get your coat.'] },

  // Grade 3
  'bird': { t: 'n. 鸟', u: '用作名词，有羽毛的飞行动物。', e: ['The bird is singing.', 'A bird flew away.'] },
  'cook': { t: 'v. 烹调', u: '用作动词，制作食物。', e: ['My mother likes to cook.', 'He cooked a delicious meal.'] },
  'duck': { t: 'n. 鸭子', u: '用作名词，水禽。', e: ['Look at the yellow duck.', 'The duck is swimming.'] },
  'easy': { t: 'adj. 容易的', u: '用作形容词，不困难的。', e: ['The test was easy.', 'It is easy to learn.'] },
  'four': { t: 'num. 四', u: '用作数词，数字 4。', e: ['I have four apples.', 'He is four years old.'] },
  'game': { t: 'n. 游戏', u: '用作名词，娱乐活动。', e: ['Let us play a game.', 'It was a fun game.'] },
  'hair': { t: 'n. 头发', u: '用作名词，长在头上的毛发。', e: ['She has long hair.', 'He brushed his hair.'] },
  'idea': { t: 'n. 想法', u: '用作名词，主意或概念。', e: ['That is a good idea.', 'I have no idea.'] },
  'joke': { t: 'n. 笑话', u: '用作名词，逗人笑的话。', e: ['He told a funny joke.', 'It was just a joke.'] },
  'keep': { t: 'v. 保持', u: '用作动词，保留或维持状态。', e: ['Keep the door closed.', 'Keep up the good work.'] },
  'lake': { t: 'n. 湖', u: '用作名词，内陆水体。', e: ['We swam in the lake.', 'The lake is beautiful.'] },
  'meat': { t: 'n. 肉', u: '用作名词，食用的动物肉。', e: ['I do not eat meat.', 'The meat is fresh.'] },
  'nice': { t: 'adj. 好的，友好的', u: '用作形容词，令人愉快的。', e: ['Have a nice day.', 'He is a nice person.'] },
  'over': { t: 'prep. 在...上方', u: '用作介词，表示位置或越过。', e: ['The plane flew over the house.', 'Game is over.'] },
  'park': { t: 'n. 公园', u: '用作名词，供公众游息的地方。', e: ['Let us walk in the park.', 'They played at the park.'] },
  'quiet': { t: 'adj. 安静的', u: '用作形容词，没有声音的。', e: ['Please be quiet.', 'It is a quiet room.'] },
  'rain': { t: 'n. 雨', u: '用作名词，降水。', e: ['It looks like rain.', 'The rain is falling.'] },
  'song': { t: 'n. 歌曲', u: '用作名词，供演唱的音乐。', e: ['She sang a beautiful song.', 'I love this song.'] },
  'tall': { t: 'adj. 高的', u: '用作形容词，高度大。', e: ['He is very tall.', 'Look at that tall building.'] },
  'use': { t: 'v. 使用', u: '用作动词，利用某物。', e: ['May I use your pen?', 'Learn to use it well.'] },
  'very': { t: 'adv. 非常', u: '用作副词，表示程度深。', e: ['I am very happy.', 'It is very cold.'] },
  'walk': { t: 'v. 走', u: '用作动词，步行。', e: ['Let us walk home.', 'He likes to walk his dog.'] },
  'yard': { t: 'n. 院子', u: '用作名词，房屋前后的空地。', e: ['The kids are playing in the yard.', 'Clean the front yard.'] },
  'zero': { t: 'num. 零', u: '用作数词，数字 0。', e: ['The score was three to zero.', 'It is zero degrees outside.'] },
  'bear': { t: 'n. 熊', u: '用作名词，一种大型哺乳动物。', e: ['We saw a bear in the forest.', 'The bear is sleeping.'] },
  'cold': { t: 'adj. 冷的', u: '用作形容词，温度低。', e: ['It is cold outside.', 'I caught a cold.'] },
  'day': { t: 'n. 天', u: '用作名词，白天或一日。', e: ['What a beautiful day.', 'He worked all day.'] },
  'end': { t: 'n. 结束', u: '用作名词，终点或结尾。', e: ['This is the end of the story.', 'Turn left at the end of the road.'] },
  'fly': { t: 'v. 飞', u: '用作动词，在空中移动。', e: ['Birds can fly.', 'I will fly to New York.'] },
  'give': { t: 'v. 给', u: '用作动词，交与。', e: ['Give me the book.', 'She gave him a gift.'] },

  // Grade 4
  'black': { t: 'adj. 黑色的', u: '用作形容词，表示颜色。', e: ['He wore a black hat.', 'The night is black.'] },
  'clean': { t: 'adj. 干净的', u: '用作形容词，无污垢的。', e: ['Keep your room clean.', 'Wash it until it is clean.'] },
  'drink': { t: 'v. 喝', u: '用作动词，饮用液体。', e: ['Drink some water.', 'He likes to drink tea.'] },
  'early': { t: 'adv. 早', u: '用作副词，在预期之前。', e: ['Wake up early.', 'She arrived early.'] },
  'fast': { t: 'adj. 快的', u: '用作形容词，速度快。', e: ['He runs fast.', 'It is a fast car.'] },
  'great': { t: 'adj. 伟大的', u: '用作形容词，非常好的。', e: ['That is a great idea.', 'He did a great job.'] },
  'happy': { t: 'adj. 快乐的', u: '用作形容词，感到高兴的。', e: ['I am so happy.', 'Happy birthday!'] },
  'into': { t: 'prep. 进入', u: '用作介词，表示向内。', e: ['He walked into the room.', 'Pour the water into the cup.'] },
  'join': { t: 'v. 参加', u: '用作动词，加入某群体。', e: ['Join us for dinner.', 'He wants to join the club.'] },
  'kind': { t: 'adj. 善良的', u: '用作形容词，友好的。', e: ['She is very kind.', 'Be kind to animals.'] },
  'love': { t: 'v. 爱', u: '用作动词，深爱。', e: ['I love my family.', 'She loves music.'] },
  'much': { t: 'adv. 很多', u: '用作副词，数量大。', e: ['Thank you very much.', 'I do not have much time.'] },
  'need': { t: 'v. 需要', u: '用作动词，必须有。', e: ['I need your help.', 'Plants need water.'] },
  'only': { t: 'adv. 仅仅', u: '用作副词，只有。', e: ['I have only one apple.', 'Only you can do this.'] },
  'play': { t: 'v. 玩', u: '用作动词，进行游戏或运动。', e: ['Let us play soccer.', 'She plays the piano.'] },
  'quite': { t: 'adv. 相当', u: '用作副词，十分。', e: ['It is quite cold today.', 'I am quite sure.'] },
  'read': { t: 'v. 读', u: '用作动词，阅读文字。', e: ['Read the book carefully.', 'He loves to read.'] },
  'show': { t: 'v. 展示', u: '用作动词，给人看。', e: ['Show me your picture.', 'The map shows the way.'] },
  'take': { t: 'v. 拿', u: '用作动词，携带或取走。', e: ['Take your umbrella.', 'Take a seat.'] },
  'upon': { t: 'prep. 在...之上', u: '用作介词，同 on。', e: ['Once upon a time.', 'He placed it upon the desk.'] },
  'view': { t: 'n. 视野，景色', u: '用作名词，看到的景象。', e: ['The view from here is beautiful.', 'In my view, it is wrong.'] },
  'want': { t: 'v. 想要', u: '用作动词，希望得到。', e: ['I want an ice cream.', 'What do you want?'] },
  'yellow': { t: 'adj. 黄色的', u: '用作形容词，表示颜色。', e: ['The sun is yellow.', 'She wore a yellow dress.'] },
  'able': { t: 'adj. 能够的', u: '用作形容词，有能力的。', e: ['I am able to do it.', 'He is an able worker.'] },
  'blue': { t: 'adj. 蓝色的', u: '用作形容词，表示颜色。', e: ['The sky is blue.', 'She has blue eyes.'] },
  'come': { t: 'v. 来', u: '用作动词，到达某地。', e: ['Come here.', 'Spring has come.'] },
  'draw': { t: 'v. 画', u: '用作动词，绘制。', e: ['Draw a circle.', 'She likes to draw.'] },
  'even': { t: 'adv. 甚至', u: '用作副词，强调语气。', e: ['Even a child knows that.', 'It is even better.'] },
  'feel': { t: 'v. 感觉', u: '用作动词，感知。', e: ['I feel sick.', 'How do you feel today?'] },
  'glad': { t: 'adj. 高兴的', u: '用作形容词，感到愉快。', e: ['I am glad to see you.', 'She was glad to help.'] },

  // Grade 5
  'bread': { t: 'n. 面包', u: '用作名词，烘焙食品。', e: ['I eat bread for breakfast.', 'Buy some fresh bread.'] },
  'clear': { t: 'adj. 清晰的', u: '用作形容词，明白的。', e: ['The water is clear.', 'Make your answer clear.'] },
  'drive': { t: 'v. 驾驶', u: '用作动词，操纵车辆。', e: ['He drives a truck.', 'Let us drive to the beach.'] },
  'earth': { t: 'n. 地球', u: '用作名词，人类居住的星球。', e: ['The earth is round.', 'Protect our earth.'] },
  'find': { t: 'v. 找到', u: '用作动词，发现某物。', e: ['I cannot find my keys.', 'Did you find it?'] },
  'green': { t: 'adj. 绿色的', u: '用作形容词，表示颜色。', e: ['The grass is green.', 'She has a green bag.'] },
  'heart': { t: 'n. 心', u: '用作名词，人体器官或中心。', e: ['My heart beats fast.', 'He has a kind heart.'] },
  'iron': { t: 'n. 铁', u: '用作名词，一种金属。', e: ['The gate is made of iron.', 'Strike while the iron is hot.'] },
  'just': { t: 'adv. 仅仅，刚刚', u: '用作副词，强调不多或时间近。', e: ['I just arrived.', 'It is just a game.'] },
  'know': { t: 'v. 知道', u: '用作动词，了解事实。', e: ['I do not know him.', 'Do you know the answer?'] },
  'look': { t: 'v. 看', u: '用作动词，注视。', e: ['Look at the picture.', 'She looks tired.'] },
  'must': { t: 'v. 必须', u: '用作情态动词，表示义务。', e: ['You must go now.', 'I must finish this.'] },
  'never': { t: 'adv. 从不', u: '用作副词，表示否定。', e: ['I never lie.', 'Never give up.'] },
  'other': { t: 'adj. 其他的', u: '用作形容词，指另外的。', e: ['Show me the other one.', 'Some boys like it, others do not.'] },
  'point': { t: 'v. 指出', u: '用作动词，指明方向。', e: ['Point to the door.', 'He made a good point.'] },
  'ready': { t: 'adj. 准备好的', u: '用作形容词，状态完成。', e: ['Are you ready?', 'Dinner is ready.'] },
  'right': { t: 'adj. 正确的', u: '用作形容词，无误的。', e: ['That is the right answer.', 'Turn right here.'] },
  'sleep': { t: 'v. 睡觉', u: '用作动词，进入睡眠状态。', e: ['I need to sleep.', 'He sleeps deeply.'] },
  'teach': { t: 'v. 教', u: '用作动词，传授知识。', e: ['Can you teach me?', 'She teaches English.'] },
  'under': { t: 'prep. 在...下面', u: '用作介词，表示位置。', e: ['The cat is under the table.', 'Look under the bed.'] },
  'visit': { t: 'v. 参观', u: '用作动词，拜访。', e: ['I will visit my grandma.', 'Come and visit us.'] },
  'watch': { t: 'v. 观看', u: '用作动词，注意看。', e: ['Watch out!', 'Let us watch a movie.'] },
  'young': { t: 'adj. 年轻的', u: '用作形容词，年龄小。', e: ['He is a young man.', 'The tree is still young.'] },
  'about': { t: 'prep. 关于', u: '用作介词，涉及。', e: ['Tell me about it.', 'It is about time.'] },
  'board': { t: 'n. 木板', u: '用作名词，平板。', e: ['Write it on the board.', 'Cut the board in half.'] },
  'color': { t: 'n. 颜色', u: '用作名词，色彩。', e: ['What color is it?', 'I like this color.'] },
  'dream': { t: 'n. 梦', u: '用作名词，睡眠中的幻象。', e: ['I had a bad dream.', 'Follow your dreams.'] },
  'ever': { t: 'adv. 曾经', u: '用作副词，在任何时候。', e: ['Have you ever been there?', 'Nothing ever happens.'] },
  'field': { t: 'n. 田地', u: '用作名词，空旷的场地。', e: ['The cows are in the field.', 'It is a football field.'] },
  'glass': { t: 'n. 玻璃', u: '用作名词，透明材料。', e: ['The window is made of glass.', 'I need a glass of water.'] },

  // Grade 6
  'brown': { t: 'adj. 棕色的', u: '用作形容词，表示颜色。', e: ['The bear is brown.', 'He has brown eyes.'] },
  'close': { t: 'v. 关', u: '用作动词，闭合。', e: ['Close the door.', 'The shop is closed.'] },
  'eight': { t: 'num. 八', u: '用作数词，数字 8。', e: ['I have eight books.', 'He woke up at eight.'] },
  'first': { t: 'num. 第一', u: '用作序数词，首要的。', e: ['He won first place.', 'First, wash your hands.'] },
  'group': { t: 'n. 组，群', u: '用作名词，聚集的人或物。', e: ['A group of people.', 'Work in a group.'] },
  'heavy': { t: 'adj. 重的', u: '用作形容词，分量大。', e: ['This box is heavy.', 'It was a heavy rain.'] },
  'item': { t: 'n. 项目', u: '用作名词，物品或条款。', e: ['Check each item.', 'Buy this item.'] },
  'large': { t: 'adj. 大的', u: '用作形容词，体积或面积大。', e: ['A large house.', 'The shirt is too large.'] },
  'make': { t: 'v. 制造', u: '用作动词，生产或导致。', e: ['Make a cake.', 'Do not make a noise.'] },
  'new': { t: 'adj. 新的', u: '用作形容词，没用过的。', e: ['I bought a new car.', 'Happy new year!'] },
  'out': { t: 'adv. 在外', u: '用作副词，向外。', e: ['Go out and play.', 'The secret is out.'] },
  'price': { t: 'n. 价格', u: '用作名词，物品的价值。', e: ['What is the price?', 'The price is too high.'] },
  'real': { t: 'adj. 真实的', u: '用作形容词，不是假的。', e: ['Is it a real diamond?', 'In real life.'] },
  'river': { t: 'n. 河流', u: '用作名词，天然水道。', e: ['Swim in the river.', 'The river is deep.'] },
  'small': { t: 'adj. 小的', u: '用作形容词，体积不大。', e: ['A small bird.', 'The room is too small.'] },
  'tell': { t: 'v. 告诉', u: '用作动词，讲述。', e: ['Tell me a story.', 'I will tell him.'] },
  'until': { t: 'prep. 直到', u: '用作介词，表示时间限制。', e: ['Wait until tomorrow.', 'Do not stop until you finish.'] },
  'voice': { t: 'n. 声音', u: '用作名词，人说话或唱歌的声音。', e: ['She has a sweet voice.', 'Lower your voice.'] },
  'your': { t: 'pron. 你的', u: '用作代词，表示所属。', e: ['Is this your book?', 'Wash your hands.'] },
  'above': { t: 'prep. 在...上方', u: '用作介词，高于。', e: ['The picture is above the bed.', 'Look above you.'] },
  'boat': { t: 'n. 船', u: '用作名词，水上交通工具。', e: ['Row the boat.', 'We rented a small boat.'] },
  'cross': { t: 'v. 穿过', u: '用作动词，越过。', e: ['Cross the street carefully.', 'Mark it with a cross.'] },
  'dress': { t: 'n. 连衣裙', u: '用作名词，女性服装。', e: ['She wore a red dress.', 'Dress warmly.'] },
  'every': { t: 'adj. 每一个', u: '用作形容词，指全体中的各个。', e: ['Every child gets a toy.', 'I run every day.'] },
  'fight': { t: 'v. 战斗', u: '用作动词，交战。', e: ['They fight for freedom.', 'Do not fight with him.'] },
  'going': { t: 'v. 正在去', u: '用作动词，go 的现在分词。', e: ['I am going home.', 'Where are you going?'] },

  // Grade 7
  'build': { t: 'v. 建造', u: '用作动词，构筑。', e: ['Build a house.', 'They build bridges.'] },
  'cloud': { t: 'n. 云', u: '用作名词，天空中的水汽。', e: ['Look at the white cloud.', 'The sky is full of clouds.'] },
  'empty': { t: 'adj. 空的', u: '用作形容词，没有东西的。', e: ['The box is empty.', 'An empty room.'] },
  'enjoy': { t: 'v. 享受', u: '用作动词，喜爱。', e: ['Enjoy your meal.', 'I enjoy reading.'] },
  'floor': { t: 'n. 地板', u: '用作名词，室内的地面。', e: ['Sweep the floor.', 'My room is on the second floor.'] },
  'grow': { t: 'v. 生长', u: '用作动词，发育或种植。', e: ['Plants need water to grow.', 'He has grown tall.'] },
  'hello': { t: 'int. 你好', u: '用作感叹词，打招呼。', e: ['Hello, how are you?', 'Say hello to him.'] },
  'kick': { t: 'v. 踢', u: '用作动词，用脚打。', e: ['Kick the ball.', 'He gave it a hard kick.'] },
  'late': { t: 'adj. 晚的', u: '用作形容词，迟到。', e: ['Hurry, we are late.', 'It is getting late.'] },
  'many': { t: 'adj. 许多的', u: '用作形容词，数量多。', e: ['I have many friends.', 'How many do you need?'] },
  'near': { t: 'prep. 在...附近', u: '用作介词，距离近。', e: ['My house is near the park.', 'Come near me.'] },
  'next': { t: 'adj. 下一个的', u: '用作形容词，紧接的。', e: ['See you next time.', 'The next station.'] },
  'page': { t: 'n. 页', u: '用作名词，书本的一面。', e: ['Turn to page ten.', 'Read the next page.'] },
  'plant': { t: 'n. 植物', u: '用作名词，草木。', e: ['Water the plant.', 'We plant trees in spring.'] },
  'reason': { t: 'n. 理由', u: '用作名词，原因。', e: ['Give me a reason.', 'That is the reason why.'] },
  'road': { t: 'n. 道路', u: '用作名词，供通行的路。', e: ['Drive on the road.', 'A long road ahead.'] },
  'smile': { t: 'v. 微笑', u: '用作动词，脸部露出笑容。', e: ['She smiled at me.', 'A friendly smile.'] },
  'thank': { t: 'v. 感谢', u: '用作动词，表达感激。', e: ['Thank you very much.', 'We thank him for his help.'] },
  'usual': { t: 'adj. 通常的', u: '用作形容词，惯常的。', e: ['As usual, he is late.', 'The usual time.'] },
  'wait': { t: 'v. 等待', u: '用作动词，期盼。', e: ['Wait for me.', 'I cannot wait anymore.'] },
  'white': { t: 'adj. 白色的', u: '用作形容词，表示颜色。', e: ['A white shirt.', 'Snow is white.'] },
  'youth': { t: 'n. 青春', u: '用作名词，年轻时期。', e: ['The youth of today.', 'He spent his youth there.'] },
  'after': { t: 'prep. 在...之后', u: '用作介词，时间或顺序在后。', e: ['After dinner.', 'Day after day.'] },
  'body': { t: 'n. 身体', u: '用作名词，躯体。', e: ['Keep your body healthy.', 'The human body.'] },
  'crowd': { t: 'n. 人群', u: '用作名词，聚集的人。', e: ['A large crowd.', 'Lost in the crowd.'] },
  'exact': { t: 'adj. 准确的', u: '用作形容词，精确无误。', e: ['The exact time.', 'Be exact in your answer.'] },
  'final': { t: 'adj. 最终的', u: '用作形容词，最后的。', e: ['The final exam.', 'My final answer.'] },
  'grand': { t: 'adj. 宏伟的', u: '用作形容词，盛大的。', e: ['A grand building.', 'The grand opening.'] },

  // Grade 8
  'carry': { t: 'v. 携带', u: '用作动词，搬运。', e: ['Carry this bag for me.', 'He carries a gun.'] },
  'coast': { t: 'n. 海岸', u: '用作名词，陆地边缘。', e: ['The west coast.', 'We drove along the coast.'] },
  'enemy': { t: 'n. 敌人', u: '用作名词，敌对者。', e: ['Fight the enemy.', 'Make no enemies.'] },
  'enter': { t: 'v. 进入', u: '用作动词，走入。', e: ['Enter the room.', 'Please do not enter.'] },
  'flower': { t: 'n. 花', u: '用作名词，植物的花朵。', e: ['A beautiful flower.', 'Water the flowers.'] },
  'guess': { t: 'v. 猜测', u: '用作动词，推测。', e: ['Guess what I have.', 'It is just a guess.'] },
  'help': { t: 'v. 帮助', u: '用作动词，援助。', e: ['Can you help me?', 'Thank you for your help.'] },
  'image': { t: 'n. 图像', u: '用作名词，形象。', e: ['A clear image.', 'Build a good image.'] },
  'kill': { t: 'v. 杀死', u: '用作动词，致死。', e: ['Do not kill animals.', 'The cold will kill the plants.'] },
  'laugh': { t: 'v. 大笑', u: '用作动词，发出笑声。', e: ['They laugh out loud.', 'A hearty laugh.'] },
  'mark': { t: 'n. 记号', u: '用作名词，标志。', e: ['Make a mark here.', 'A question mark.'] },
  'night': { t: 'n. 夜晚', u: '用作名词，黑夜。', e: ['Good night.', 'Sleep well at night.'] },
  'paper': { t: 'n. 纸', u: '用作名词，书写材料。', e: ['Write on the paper.', 'A piece of paper.'] },
  'plate': { t: 'n. 盘子', u: '用作名词，盛食物的器皿。', e: ['A clean plate.', 'Put it on my plate.'] },
  'record': { t: 'v. 记录', u: '用作动词，记载。', e: ['Record the score.', 'Set a new record.'] },
  'rock': { t: 'n. 岩石', u: '用作名词，石头。', e: ['A hard rock.', 'Climb the rock.'] },
  'sound': { t: 'n. 声音', u: '用作名词，声响。', e: ['A loud sound.', 'Sound travels fast.'] },
  'their': { t: 'pron. 他们的', u: '用作代词，表示所属。', e: ['Their house is big.', 'It is their turn.'] },
  'value': { t: 'n. 价值', u: '用作名词，有用性。', e: ['The value of money.', 'Value your time.'] },
  'wake': { t: 'v. 醒来', u: '用作动词，睡醒。', e: ['Wake up early.', 'Do not wake him.'] },
  'whole': { t: 'adj. 整个的', u: '用作形容词，全部。', e: ['The whole world.', 'Tell the whole truth.'] },
  'yours': { t: 'pron. 你的', u: '用作代词，你的东西。', e: ['The book is yours.', 'Is this yours?'] },
  'again': { t: 'adv. 再一次', u: '用作副词，重新。', e: ['Try again.', 'See you again.'] },
  'bone': { t: 'n. 骨头', u: '用作名词，骨骼。', e: ['A dog chewing a bone.', 'Broken bone.'] },
  'crown': { t: 'n. 王冠', u: '用作名词，国王的帽子。', e: ['The king wears a crown.', 'A golden crown.'] },
  'exist': { t: 'v. 存在', u: '用作动词，实际有。', e: ['Do ghosts exist?', 'It no longer exists.'] },
  'grant': { t: 'v. 授予', u: '用作动词，同意给予。', e: ['Grant a wish.', 'Take it for granted.'] },

  // Grade 9
  'catch': { t: 'v. 抓住', u: '用作动词，捕捉。', e: ['Catch the ball.', 'Catch a cold.'] },
  'cover': { t: 'v. 覆盖', u: '用作动词，遮盖。', e: ['Cover the pot.', 'Read from cover to cover.'] },
  'engine': { t: 'n. 引擎', u: '用作名词，发动机。', e: ['Start the engine.', 'A powerful engine.'] },
  'event': { t: 'n. 事件', u: '用作名词，发生的事。', e: ['A major event.', 'In the event of fire.'] },
  'force': { t: 'n. 力量', u: '用作名词，力气。', e: ['Use force.', 'May the force be with you.'] },
  'guest': { t: 'n. 客人', u: '用作名词，宾客。', e: ['Be my guest.', 'A special guest.'] },
  'high': { t: 'adj. 高的', u: '用作形容词，高度大。', e: ['A high mountain.', 'Jump high.'] },
  'issue': { t: 'n. 问题', u: '用作名词，议题。', e: ['A complex issue.', 'The latest issue.'] },
  'king': { t: 'n. 国王', u: '用作名词，男性君主。', e: ['The king ruled the land.', 'A wise king.'] },
  'learn': { t: 'v. 学习', u: '用作动词，获取知识。', e: ['Learn English.', 'Learn from mistakes.'] },
  'mean': { t: 'v. 意思是', u: '用作动词，意味着。', e: ['What do you mean?', 'I mean it.'] },
  'noise': { t: 'n. 噪音', u: '用作名词，吵闹声。', e: ['Make a loud noise.', 'Stop that noise.'] },
  'party': { t: 'n. 聚会', u: '用作名词，派对。', e: ['A birthday party.', 'Let us have a party.'] },
  'please': { t: 'adv. 请', u: '用作副词，表示客气。', e: ['Help me, please.', 'Yes, please.'] },
  'region': { t: 'n. 地区', u: '用作名词，区域。', e: ['A dry region.', 'The whole region.'] },
  'roll': { t: 'v. 滚动', u: '用作动词，转动。', e: ['Roll the ball.', 'A roll of paper.'] },
  'south': { t: 'n. 南方', u: '用作名词，方位。', e: ['Go south.', 'The south wind.'] },
  'there': { t: 'adv. 那里', u: '用作副词，那个地方。', e: ['Over there.', 'There is a book.'] },
  'wall': { t: 'n. 墙', u: '用作名词，建筑物的隔断。', e: ['A high wall.', 'Paint the wall.'] },
  'whose': { t: 'pron. 谁的', u: '用作代词，表示所属。', e: ['Whose book is this?', 'I know whose it is.'] },
  'against': { t: 'prep. 反对', u: '用作介词，靠着或对抗。', e: ['Fight against them.', 'Lean against the wall.'] },
  'curve': { t: 'n. 曲线', u: '用作名词，弯曲。', e: ['A sharp curve.', 'Draw a curve.'] },
  'drop': { t: 'v. 落下', u: '用作动词，掉下。', e: ['Do not drop it.', 'A drop of water.'] },
  'extra': { t: 'adj. 额外的', u: '用作形容词，附加的。', e: ['Extra time.', 'Need extra help.'] },
  'fixed': { t: 'adj. 固定的', u: '用作形容词，确定的。', e: ['A fixed price.', 'Keep it fixed.'] },
  'grasp': { t: 'v. 抓住', u: '用作动词，领会。', e: ['Grasp the rope.', 'Grasp the meaning.'] }
};

const gradesData = {
  1: ['apple', 'book', 'cat', 'dog', 'egg', 'fish', 'girl', 'hand', 'ice', 'juice', 'kite', 'lion', 'milk', 'nose', 'orange', 'pig', 'queen', 'red', 'sun', 'tree', 'box', 'cup', 'desk', 'eye', 'face', 'jump', 'key'],
  2: ['bike', 'cake', 'door', 'ear', 'foot', 'good', 'head', 'kiss', 'leg', 'moon', 'name', 'open', 'pen', 'quick', 'room', 'star', 'time', 'van', 'water', 'xray', 'year', 'zoo', 'bag', 'car', 'dad', 'eat', 'fat', 'get'],
  3: ['bird', 'cook', 'duck', 'easy', 'four', 'game', 'hair', 'idea', 'joke', 'keep', 'lake', 'meat', 'nice', 'over', 'park', 'quiet', 'rain', 'song', 'tall', 'use', 'very', 'walk', 'yard', 'zero', 'bear', 'cold', 'day', 'end', 'fly', 'give'],
  4: ['black', 'clean', 'drink', 'early', 'fast', 'great', 'happy', 'into', 'join', 'kind', 'love', 'much', 'need', 'only', 'play', 'quite', 'read', 'show', 'take', 'upon', 'view', 'want', 'yellow', 'able', 'blue', 'come', 'draw', 'even', 'feel', 'glad'],
  5: ['bread', 'clear', 'drive', 'earth', 'find', 'green', 'heart', 'iron', 'just', 'know', 'look', 'must', 'never', 'other', 'point', 'ready', 'right', 'sleep', 'teach', 'under', 'visit', 'watch', 'young', 'about', 'board', 'color', 'dream', 'ever', 'field', 'glass'],
  6: ['brown', 'close', 'eight', 'first', 'group', 'heavy', 'item', 'large', 'make', 'new', 'out', 'price', 'real', 'river', 'small', 'tell', 'until', 'voice', 'your', 'above', 'boat', 'cross', 'dress', 'every', 'fight', 'going'],
  7: ['build', 'cloud', 'empty', 'enjoy', 'floor', 'grow', 'hello', 'kick', 'late', 'many', 'near', 'next', 'page', 'plant', 'reason', 'road', 'smile', 'thank', 'usual', 'wait', 'white', 'youth', 'after', 'body', 'crowd', 'exact', 'final', 'grand'],
  8: ['carry', 'coast', 'enemy', 'enter', 'flower', 'guess', 'help', 'image', 'kill', 'laugh', 'mark', 'night', 'paper', 'plate', 'record', 'rock', 'sound', 'their', 'value', 'wake', 'whole', 'yours', 'again', 'bone', 'crown', 'exist', 'grant'],
  9: ['catch', 'cover', 'engine', 'event', 'force', 'guest', 'high', 'issue', 'king', 'learn', 'mean', 'noise', 'party', 'please', 'region', 'roll', 'south', 'there', 'wall', 'whose', 'against', 'curve', 'drop', 'extra', 'fixed', 'grasp']
};

const dir = path.join(__dirname, 'src/data/words');
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

for (let grade = 1; grade <= 9; grade++) {
  const wordsList = gradesData[grade] || [];
  const words = wordsList.map((word) => {
    const entry = dictionary[word] || { t: `这是${word}的翻译`, u: `作名词时指...，作动词时指...`, e: [`This is an example for ${word}.`, `He likes ${word}.`] };
    return {
      word: word,
      translation: entry.t,
      usage: entry.u,
      examples: entry.e
    };
  });
  fs.writeFileSync(path.join(dir, `grade${grade}.json`), JSON.stringify(words, null, 2));
}

console.log('Generated real words data with translations and usages.');